---
# vars file for vim
vim_dir: "{{ ansible_env.HOME }}/.vim"
vimrc: "{{ ansible_env.HOME }}/.vimrc"
nvimrc: "{{ ansible_env.HOME }}/.config/nvim"
nvimplug: "{{ ansible_env.HOME }}/.config/nvim/pack"
perltidyrc: "{{ ansible_env.HOME }}/.perltidyrc"
pkg_become: >-
  {% if ansible_facts.distribution == 'Archlinux' %}
  no
  {% elif ansible_facts.distribution == 'MacOSX' %}
  no
  {% else %}
  yes
  {% endif %}
pkg_become_user: >-
  {% if ansible_facts.distribution == 'Archlinux' %}
  ansible_facts.env.USER
  {% elif ansible_facts.distribution == 'MacOSX' %}
  ansible_facts.env.USER
  {% endif %}
