---
# Packages for Debian and Ubuntu
pkg_list:
  - vim
  - neovim
  - git
  - powerline
  - fzf
  - jq
  - fonts-powerline
  - python3-autopep8
  - perltidy
  - libtest-perl-critic-perl
  - python3-pytest-pylint
  - shellcheck
  - yamllint
  - ansible-lint
